#!/usr/bin/env bash
# ============================================================================
# CivicPulseAI — Environment File Generator
# ============================================================================
# Generates required .env files for Docker Compose when they are missing
# (e.g., after a fresh git clone in CI/CD where .env is gitignored).
#
# Uses .env.example as a template when available, otherwise generates
# defaults suitable for the Docker Compose environment.
#
# Called by Jenkinsfile Stage 2 (Environment Validation).
# ============================================================================
set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info()  { echo -e "${CYAN}[ENV-GEN]${NC} $*"; }
log_ok()    { echo -e "${GREEN}[ENV-GEN]${NC} ✅ $*"; }
log_warn()  { echo -e "${YELLOW}[ENV-GEN]${NC} ⚠️  $*"; }

# ── Configurable via environment variables or Jenkins credentials ─────────────
# These can be overridden by Jenkins environment variables or credentials
DEPLOY_ENV="${DEPLOY_ENV:-development}"
MONGODB_HOST="${MONGODB_HOST:-mongodb}"
MONGODB_PORT="${MONGODB_PORT:-27017}"
MONGODB_DB="${MONGODB_DB:-civicpulse}"
BACKEND_PORT="${BACKEND_PORT:-3000}"
JWT_ACCESS_SECRET="${JWT_ACCESS_SECRET:-civicpulse-ci-access-secret-$(date +%s)}"
JWT_REFRESH_SECRET="${JWT_REFRESH_SECRET:-civicpulse-ci-refresh-secret-$(date +%s)}"
CORS_ORIGIN="${CORS_ORIGIN:-http://localhost:4200}"
LOG_LEVEL="${LOG_LEVEL:-debug}"

echo ""
echo "════════════════════════════════════════"
echo "  🔧 Environment File Generator"
echo "════════════════════════════════════════"
echo ""

# ── Generate backend/.env ─────────────────────────────────────────────────────
if [ -f "backend/.env" ]; then
    log_info "backend/.env already exists — skipping generation"
else
    log_info "Generating backend/.env..."

    # Use .env.example as base if available, then override Docker-specific values
    if [ -f "backend/.env.example" ]; then
        log_info "  Using backend/.env.example as template"
        cp backend/.env.example backend/.env

        # Override MONGODB_URI for Docker networking (service name instead of localhost)
        sed -i "s|MONGODB_URI=.*|MONGODB_URI=mongodb://${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DB}|" backend/.env
        sed -i "s|NODE_ENV=.*|NODE_ENV=${DEPLOY_ENV}|" backend/.env
        sed -i "s|JWT_ACCESS_SECRET=.*|JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}|" backend/.env
        sed -i "s|JWT_REFRESH_SECRET=.*|JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}|" backend/.env
    else
        # Generate from scratch
        log_warn "  No .env.example found — generating defaults"
        cat > backend/.env <<EOF
# Server
NODE_ENV=${DEPLOY_ENV}
PORT=3000

# MongoDB
MONGODB_URI=mongodb://${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DB}

# JWT
JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
JWT_ACCESS_EXPIRY=15m
JWT_REFRESH_EXPIRY=7d

# CORS
CORS_ORIGIN=${CORS_ORIGIN}

# Reset Password
DEFAULT_PASSWORD=${DEFAULT_PASSWORD:-CivicPulse@2026}

# Logging
LOG_LEVEL=${LOG_LEVEL}
EOF
    fi

    log_ok "backend/.env generated successfully"
    echo "  Contents (secrets masked):"
    sed 's/\(SECRET=\).*/\1********/' backend/.env | sed 's/^/    /'
fi

echo ""

# ── Generate frontend/.env ────────────────────────────────────────────────────
if [ -f "frontend/.env" ]; then
    log_info "frontend/.env already exists — skipping generation"
else
    log_info "Generating frontend/.env..."

    cat > frontend/.env <<EOF
# Frontend Environment Variables (Auto-generated by CI/CD pipeline)
NODE_ENV=${DEPLOY_ENV}
API_URL=http://localhost:${BACKEND_PORT}/api

# Stubbed backend variables required by Docker Compose env_file
PORT=3000
MONGODB_URI=mongodb://${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DB}
JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
JWT_ACCESS_EXPIRY=15m
JWT_REFRESH_EXPIRY=7d
SMTP_HOST=smtp.mailtrap.io
SMTP_PORT=2525
SMTP_USER=user
SMTP_PASS=pass
AI_API_KEY=your-ai-api-key-here
EOF

    log_ok "frontend/.env generated successfully"
fi

echo ""

# ── Verify generated files ───────────────────────────────────────────────────
MISSING=0
for envfile in backend/.env frontend/.env; do
    if [ -f "$envfile" ]; then
        log_ok "$envfile exists ($(wc -l < "$envfile") lines)"
    else
        log_warn "$envfile — STILL MISSING after generation!"
        MISSING=$((MISSING + 1))
    fi
done

echo ""
if [ $MISSING -gt 0 ]; then
    echo "❌ FATAL: $MISSING .env file(s) could not be generated"
    exit 1
fi

log_ok "═══════════════════════════════════════════════════"
log_ok "  All environment files ready"
log_ok "═══════════════════════════════════════════════════"
