apiVersion: v1
kind: Secret
metadata:
  name: {{ include "civicpulse.fullname" . }}-secret
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "civicpulse.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_ACCESS_SECRET: {{ .Values.secret.jwtAccessSecret | quote }}
  JWT_REFRESH_SECRET: {{ .Values.secret.jwtRefreshSecret | quote }}
  DEFAULT_PASSWORD: {{ .Values.secret.defaultPassword | quote }}
