FROM mongo:8.0

# Upgrade OS packages to pull latest security patches
RUN rm -rf /var/lib/apt/lists/* && \
    apt-get clean && \
    apt-get update && \
    apt-get upgrade -y && \
    rm -rf /var/lib/apt/lists/*

# Add initialization scripts
COPY mongo-init.js /docker-entrypoint-initdb.d/

# Add basic health check
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD mongosh --quiet --eval "db.adminCommand('ping')" || exit 1


