apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: civicpulse
  namespace: argocd
  labels:
    app.kubernetes.io/name: civicpulse
    app.kubernetes.io/part-of: civicpulse-ai
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=ghcr.io/tharunadhithyaa/civicpulse-frontend, backend=ghcr.io/tharunadhithyaa/civicpulse-backend
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/frontend.helm.image-tag: frontend.image.tag
    argocd-image-updater.argoproj.io/backend.helm.image-tag: backend.image.tag
    argocd-image-updater.argoproj.io/write-back-method: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tharunadhithyaa/intelligent-self-healing-cicd.git
    targetRevision: main
    path: helm/civicpulse
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: civicpulse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /spec/source/helm/parameters

