import { Pipe, PipeTransform } from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { marked } from 'marked';
import DOMPurify from 'dompurify';

@Pipe({
  name: 'markdown',
  standalone: true,
})
export class MarkdownPipe implements PipeTransform {
  constructor(private sanitizer: DomSanitizer) {}

  transform(value: string | undefined): SafeHtml {
    if (!value) return '';

    // Parse markdown to HTML
    const rawHtml = marked.parse(value) as string;

    // Sanitize raw HTML generated by marked using DOMPurify with a strict allowlist.
    // DOMPurify removes malicious scripts, event handlers, and XSS vectors.
    const cleanHtml = DOMPurify.sanitize(rawHtml, {
      ALLOWED_TAGS: [
        'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'br', 'hr',
        'span', 'div', 'code', 'pre', 'blockquote',
        'ul', 'ol', 'li',
        'table', 'thead', 'tbody', 'tr', 'th', 'td',
        'a', 'img', 'strong', 'em', 'del', 'ins', 'sub', 'sup',
      ],
      ALLOWED_ATTR: ['href', 'title', 'target', 'rel', 'src', 'alt', 'class'],
    });

    // Security explanation: bypassSecurityTrustHtml is safe here because the HTML content
    // has already been strictly sanitized by DOMPurify above, preventing any XSS vulnerabilities
    // while preserving standard Markdown HTML formatting that Angular sanitization would otherwise strip.
    return this.sanitizer.bypassSecurityTrustHtml(cleanHtml);
  }
}
